Feat/home
hattrickkk/modsen-blog pull request #2
Opened 2024-09-18 12:33 UTC by hattrickkk

2024-09-18 17:30 UTC, xYerMikx requested changes

2024-09-18 17:30 UTC, xYerMikx commented on src/entities/authors/helpers.ts
> +    })
здесь давай сделаем рандомную задержку, чтобы сымитировать реальный запрос: пускай диапазон будет 50-250 мс

2024-09-18 17:30 UTC, xYerMikx commented on src/features/slider/index.tsx
> +    const maxOffset = useMemo(() => -(TESTIMONIALS.length - 1) * 100, [])
достаточно простые вычисления, не обязательно мемоизацию использовать

2024-09-18 17:30 UTC, xYerMikx commented on src/features/subscribe/index.tsx
> +import { sendEmail } from './utilts/sendEmail'
очепятка - util**t**s -> utils

2024-09-18 17:30 UTC, xYerMikx commented on src/features/subscribe/index.tsx
> +}
zod отлично юзает infer: можно в схеме валидации экспортировать 
`export type EmailFormData = z.infer<typeof emailSchema>`

2024-09-18 17:30 UTC, xYerMikx commented on src/shared/ui/button/index.tsx
>              {children ?? 'Read More >'}
а почему children типа string? Вообще по-хорошему в children приходит `ReactNode`. + можешь по дефолту сделать 'Read More >' и не использовать оператор `??`

2024-09-18 17:30 UTC, xYerMikx commented on src/shared/ui/categoryCard/index.tsx
> +    Icon: () => ReactElement
а тип `ReactNode` для иконки не подошел ?

2024-09-18 17:30 UTC, xYerMikx commented on src/shared/ui/categoryCard/styles.module.scss
> +        letter-spacing: -0.04em;
а для чего тебе отрицательный и настолько маленький спейсинг ?

2024-09-18 20:32 UTC, hattrickkk commented on src/shared/utils/hooks/useValidateInput.ts
> +    } = useController({
не получилось :(((

2024-09-18 20:50 UTC, hattrickkk commented on src/shared/ui/categoryCard/styles.module.scss
> +        letter-spacing: -0.04em;
так в макете было :D
он для сдвига символов в тексте, я где-то убрала, где-то оставила. На маленьком шрифте не видно, но на большом текст сильно разъезжается, поэтому в некоторых местах оставила.

2024-09-19 07:03 UTC, xYerMikx approved these changes

2024-09-19 07:10 UTC, merged